// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApiApp.Models;

namespace TestApiApp.Migrations
{
    [DbContext(typeof(TestApiAppContext))]
    [Migration("20200127170141_tapi1")]
    partial class tapi1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestApiApp.Models.Platform", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<double>("latitude");

                    b.Property<double>("longitude");

                    b.Property<string>("uniqueName");

                    b.Property<DateTime?>("updatedAt");

                    b.HasKey("id");

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("TestApiApp.Models.Well", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("createdAt");

                    b.Property<double>("latitude");

                    b.Property<double>("longitude");

                    b.Property<int>("platformId");

                    b.Property<string>("uniqueName");

                    b.Property<DateTime?>("updatedAt");

                    b.HasKey("id");

                    b.ToTable("Well");
                });
#pragma warning restore 612, 618
        }
    }
}
